[package]
name = "double-sha256"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
digest = "0.10.3"
k256 = "0.11.2"
sha2 = "0.10.2"
